apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ecomovequest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ecomovequest
    app.kubernetes.io/part-of: ecomovequest
  name: ecomovequest
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: ecomovequest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: ecomovequest
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/balejosg-tenant/ecomovequest/ecomovequest@sha256:d4284d15435de17922a264bfd84ae85291aabbe6dfe920a4e88b1fe696cd3776
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
